site_name: Bash Script Collection
site_url: https://ltalignani.github.io/mkdocs-bash-scripts-collection/
repo_url: https://github.com/ltalignani/mkdocs-bash-scripts-collection
repo_name: ltalignani/bash-scripts-collection

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo_LT.png
  favicon: assets/favicon.ico
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
nav:
  - Home: index.md
  - Organize Your Data: organize-data.md
  - Start Using Git: Git.md
  - Fastq Files:
      - Fastq Format: Fastq/Fastq.md
      - Rename Fastq Files: Fastq/rename-fastq.md
      - FastQC: Fastq/FastQC.md
      - Fastq-screen: Fastq/Fastq-screen.md
      - Trimming: Fastq/Trimming.md
      - Mapping: Fastq/BWA.md
  - Bam Files:
      - Bam Format: Bam/Bam.md
      - Sorting Bam Files: Bam/sort-bam.md
      - Add or Replace Read Groups: Bam/add-or-replace-read-groups.md
      - Marking Duplicates: Bam/mark-duplicates.md
      - Merge and Mark Duplicates: Bam/merge-and-mark-duplicates.md
      - Indel Realignment: Bam/indel-realignment.md
      - Polishing Bam Files: Bam/polishing.md
      - Bam Quality Control: Bam/bam-qc.md
      - Variant Calling: Bam/variant-calling.md
      - GenomicsDBImport and GenotypeGVCFs: Bam/genomicsdbimport.md
  - VCF Files:
      - VCF Format: Vcf/Vcf.md
      - Filtering by Accessibility: Vcf/accessibility.md
      - Filtering by Homopolymer: Vcf/homopolymer.md
      - Filtering of Variants & Invariants: Vcf/variants-invariants.md
      - Filtering by Genotype Quality: Vcf/genotype-quality.md
      - VCF concatenation: Vcf/concatenate.md
      - Filtering by GT and INDV: Vcf/gt-indv.md
  - About: about.md

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - def_list

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ltalignani/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/loic-talignani-83a7581a2/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject

extra_css:
  - css/overrides.css

copyright: >
  Copyright &copy; 2025 Loïc Talignani -
  <a href="#__consent">Change cookie settings</a>
